name: Install and Run Swift Packages with Mint

on: [pull_request, push, workflow_dispatch]

jobs:
  mint:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Mint
        uses: irgaly/setup-mint@v1

      - name: SwiftFormat Lint
        run: mint run swiftformat --verbose .

      - name: Commit changes
        uses: Cement-Labs/.github/.github/actions/commit@main
        with:
          commit-message: "🎨 Format code"
