name: Install and Run Swift Packages with Mint

on: [pull_request, push, workflow_dispatch]

jobs:
  mint:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Mint
        uses: Cement-Labs/.github/.github/actions/mint@main

      - name: SwiftFormat Lint
        run: mint run swiftformat --verbose .

      - name: Commit changes
        uses: Cement-Labs/.github/.github/actions/commit@main
        with:
          commit-message: "🎨 Format code"
